name: Download catpkgs

on:
  schedule:
    - cron: 10,40 0-15,23 * * *
  workflow_dispatch:

jobs:
  work:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download
        run: |
          curl https://raw.githubusercontent.com/HenryQinUp/JK/master/Q2WForever.json > Q2WForever.json
          # 删掉盘搜
          sed -i "/csp_AliPanSou/c\\ " ./Q2WForever.json
          # 删掉小纸条
          sed -i "/csp_GitCafe/c\\ " ./Q2WForever.json
          # 删掉找资源
          sed -i "/csp_FindZY/c\\ " ./Q2WForever.json
          # 删掉推送
          sed -i "/csp_PushAgent/c\\ " ./Q2WForever.json
          # 更新时间
          sed -i "/Q2WForever.json/c\\// update time: $(date -u -d '+8 hour' '+%Y.%m.%d %H:%M:%S')" ./Q2WForever.json
        
          
          
          curl https://codeload.github.com/chengxue2020/q215613905-Tbox/zip/refs/heads/main > chengxue2020-cat.zip
          sed -i "/chengxue2020-cat.zip/c\\// update time: $(date -u -d '+8 hour' '+%Y.%m.%d %H:%M:%S')" ./chengxue2020-cat.zip

          curl https://github.com/takagen99/Box/zip/refs/heads/main > takagen99-cat.zip
          sed -i "/takagen99-cat.zip/c\\// update time: $(date -u -d '+8 hour' '+%Y.%m.%d %H:%M:%S')" ./takagen99-cat.zip
       
          

      - name: Commit And Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "update src"
          git push origin main
